apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: alck88t05-go
  janus-idp.io/tekton: alck88t05-go
  backstage.io/kubernetes-id: alck88t05-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: alck88t05-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
