apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: alck88t05-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: alck88t05-go 
  name: alck88t05-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: alck88t05-go 
